### ISSUE TITLE
Is it working ?

### ISSUE THREAD

**Issue by remfan77** [pahihu/coldfire#1]
Hello, I tried following instructions running uclinux.
Tried compiling on linux x64 and linux i386.
I have gunzipped uclinux images (small and big).
I always have the same log:

```
paolo@localhost ~/coldfire-master/install/bin $ ./coldfire
Use CTRL-C (SIGINT) to cause autovector interrupt 7 (return to monitor)
Loading memory modules...
Loading board configuration...
Board ID: Arnewsh
CPU: 5206 (Motorola Coldfire 5206)
        unimplemented instructions: CPUSHL PULSE WDDATA WDEBUG
        62 instructions registered
        building instruction cache... done.
Memory segments: dram  timer1  timer2  uart1(on port 5206)
                 uart2(on port 5207)  sim  ne2000  isa
                 rom  sram
!!! Remember to telnet to the above ports if you want to see any output!
Hard Reset...
Initializing monitor...
Enter 'help' for help.
dBug> dl /home/paolo/coldfire-master/uclinux/image-an5206-big-20000706.bin
Downloading Binary image... (offset=0x00010000)
dBug> go 10000
retr retr failed for size=32, offset=0x00400000
PC: 0001003E SR: 2709 [t.Sm.111...xNzvC]
An: 00400000 02000000 00000008 0001004A 00000000 00000000 00000000 00010000
Dn: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
```
Does it work for you ?
Best regards,
Paolo

**Comment by pahihu** [comment]
Hello,

Please read the line which begins with ‘!!!’ In your output.
You should run 'telnet localhost 5206' to see any output.

There is a file in the distro ‘ColdFireEmu_HOWTO.txt’,
It explains how to run the uCLinux images.

Regards,
pahihu

PS:

The output in the telnet window is something like:

===> gtelnet localhost 5206
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
uart1


uClinux/COLDFIRE(m5206)
COLDFIRE port done by Greg Ungerer, ***@***.***
Flat model support (C) 1998,1999 Kenneth Albanowski, D. Jeff Dionne
KERNEL -> TEXT=0x010000-0x077cb8 DATA=0x077cb8-0x08b0d0 BSS=0x08b0d0-0x0a2d58
KERNEL -> ROMFS=0x0a2d58-0x183b10 MEM=0x183b10-0x3ff000 STACK=0x3ff000-0x400000
Calibrating delay loop.. ok - 16.58 BogoMIPS
Memory available: 2476k/4096k RAM, 0k/0k ROM (415k kernel code, 172k data)
Swansea University Computer Society NET3.035 for Linux 2.0
NET3: Unix domain sockets 0.13 for Linux NET3.035.
Swansea University Computer Society TCP/IP for NET3.034
IP Protocols: ICMP, UDP, TCP
uClinux version 2.0.38.0 ***@***.***) (gcc version egcs-2.91.66 19990314 (egcs-1.1.2 release)) #3 Thu Jul 6 15:28:34 EST 2000
ColdFire internal UART serial driver version 1.00
ttyS0 at 0x10000140 (irq = 224) is a builtin ColdFire UART
ttyS1 at 0x10000180 (irq = 225) is a builtin ColdFire UART
Ramdisk driver initialized : 16 ramdisks of 4096K size
Blkmem copyright 1998,1999 D. Jeff Dionne
Blkmem copyright 1998 Kenneth Albanowski
Blkmem 2 disk images:
0: A2D58-183D57 (RO)
1: FFE20000-FFE3FFFF (RW)
PPP: version 2.3.8 (demand dialling)
TCP compression code copyright 1989 Regents of the University of California
PPP line discipline registered.
SLIP: version 0.8.4-NET3.019-NEWTTY (dynamic channels, max=256).
CSLIP: code copyright 1989 Regents of the University of California.
ne.c:v1.10 9/23/94 Donald Becker ***@***.***)
NE*000 ethercard probe at 0x40000300: 00 00 00 00 00 00
eth0: NE2000 found at 0x40000300, using IRQ 240.
VFS: Mounted root (romfs filesystem) readonly.
Shell invoked to run file: /etc/rc
Command: hostname uClinux-coldfire
Command: /bin/expand /etc/ramfs.img /dev/ram0
Command: mount -t proc proc /proc
Command: mount -t ext2 /dev/ram0 /var
Command: mkdir /var/tmp
Command: mkdir /var/log
Command: ifconfig lo 127.0.0.1
Command: route add -net 127.0.0.0 lo
Command: dhcpcd -p -a eth0 &
[11]
Command: cat /etc/motd
Welcome to
               _     _
              | |   |_|             _  _
    _   _ ____| |    _ ____  _   _ / \/ \
   | | | / ___| |   | |  _ \| | | |\    /
   | |_| | |__| |___| | | | | |_| |/    \
   |  ___\____|_____|_|_| |_|\____|\_/\_/
   | |
   |_|

     on the Motorola ColdFire processor!!

For further information check:
http://www.moretonbay.com/coldfire/linux-coldfire.html

Execution Finished, Exiting

Sash command shell (version 1.1.1)
/> ARP: arp called for own IP address
eth0: timeout waiting for Tx RDC.
eth0: ne_reset_8390() did not complete.
eth0: timeout waiting for Tx RDC.
eth0: ne_reset_8390() did not complete.

**Comment by remfan77** [comment]
Thanks for your reply.
I have already read ColdFireEmu_HOWTO.txt.
And also opened two telnet port 5206 and 5207.
On telnet windows I do not see nothing.
Is it normal the output on the main console ?

```
PC: 0001003E SR: 2709 [t.Sm.111...xNzvC]
An: 00400000 02000000 00000008 0001004A 00000000 00000000 00000000 00010000
Dn: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
```
The only difference is that I do not done "make install".
I also tried configure --prefix=xxxxx and then make install. I have to create manually install/bin directory.
Also tried ./colfire --board xxxx to point the correct board in the boards directory.
Any suggestion ?

**Comment by pahihu** [comment]
Hi,

Yes on the main console this is the normal output.
The telnet connection succeeds to the localhost ports 5206 and 5207 ?

Do you have multiple IP addresses ?
Most of the older software assumes do you have only one, and chooses
the first available interface which is usually not what you want.

I am on macOS 10.14, if you are patient, later today I can try on a virtual
CentOS 7 server box.

Regards,
pahihu

**Comment by remfan77** [comment]
```
ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.140  netmask 255.255.0.0  broadcast 10.0.255.255
        ether 00:51:c2:65:87:fa  txqueuelen 1000  (Ethernet)
        RX packets 668817  bytes 43871496 (41.8 MiB)
        RX errors 0  dropped 43242  overruns 0  frame 0
        TX packets 21  bytes 1296 (1.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
 
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 38  bytes 2336 (2.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38  bytes 2336 (2.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
The telnets are ok, that is if I telnet without coldfire I have an error.
If I launch coldfire, telnets are waiting chars from coldfire.

It is an interesting software....If you have time to try...no hurry.
Thanks again,
Paolo

**Comment by pahihu** [comment]
Hi,

Run with ./coldfire —trace network
It will output trace messages on the main console which relates to the network subsystem.
Maybe this will reveal the problem.

Regards,
pahihu

**Comment by remfan77** [comment]
The problem seems the telnet connection.
When I start the telnet client, then network_accept function does not return.
I'm digging....
Thanks
Paolo

**Comment by remfan77** [comment]
Ok, it works...
in network.c changing

if(listen(*fd,0) < 0) {
with
if(listen(*fd,10) < 0) {

I do not understand well why.
Paolo

**Comment by pahihu** [comment]
Hi,

Yes, this is strange. I can run successfully the coldfire emulator on a CentOS 7 box
without modifications.

The 0 means on the listen() call, that the implementation could use a default value
for the backlog.

Which Linux distro do you use? What is the kernel version?

Regards,
pahihu

**Comment by remfan77** [comment]
Kernel 4.12 (compiled by myself), gentoo userspace.

**Comment by pahihu** [comment]
Hi,

Thanks.
What is the output of

	cat /proc/sys/net/ipv4/tcp_syncookies

on your system?

Regards,
pahihu

**Comment by remfan77** [comment]
I do not have this voice

cat /proc/sys/net/ipv4/tcp_syn_retries
6

cat /proc/sys/net/ipv4/tcp_synack_retries
5

Probabily I commented some network kernel options.
I usually use very simple configurations.

**Comment by pahihu** [comment]
Hi,

Maybe that is the culprit, that you do not have tcp_syncookies.

It is a separate compile time option in the Linux kernel.
When tcp_syncookies is set to 1, it allows to overflow the number
of backlogs specified on the listen() call.

Since Linux 2.2, the meaning of backlog in listen() is changed: it 
specifies the number of complete TCP requests waiting on the
queue.

So when you have no tcp_syncookies setting and specify 0 for
the backlog size, it cannot accept any TCP requests.

Regards,
pahihu

**Comment by remfan77** [comment]
Could be, I'm sorry to all this. I wasted you some time. 

Best regards,
Paolo

**Comment by pahihu** [comment]
Hi,

I use Linux as well, it is always an entertaining excercise
to explore some idiosyncratic behavior.

I will close the issue.

Regards,
pahihu
